# Generated by Django 2.0.3 on 2018-05-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=25)),
                ('licence_plate', models.CharField(max_length=8)),
                ('transmission', models.CharField(max_length=25)),
                ('clas', models.CharField(max_length=25)),
                ('release_year', models.IntegerField(max_length=4)),
                ('engine_capacity', models.FloatField()),
                ('color', models.CharField(max_length=25)),
                ('price_day', models.IntegerField()),
            ],
        ),
    ]
