# Generated by Django 2.0.3 on 2018-05-23 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_auto_20180522_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.IntegerField()),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_start', models.DateField(help_text='День начала', verbose_name='День начала')),
                ('day_end', models.DateField(help_text='День окончания', verbose_name='День окончания')),
                ('pickup_point', models.CharField(help_text='Место подачи авто', max_length=255)),
                ('start_time', models.TimeField(help_text='Время начала', verbose_name='Время начала')),
                ('end_time', models.TimeField(help_text='Время окончания', verbose_name='Время окончания')),
                ('return_point', models.CharField(help_text='Место возврата авто', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Textual Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Фамилия Имя Отчество', max_length=100)),
                ('email', models.EmailField(help_text='Email', max_length=254)),
                ('phone', models.CharField(help_text='Телефон', max_length=13)),
                ('age', models.IntegerField()),
                ('passport', models.CharField(help_text='Серия и номер пасспорта', max_length=8)),
                ('driving_experience', models.FloatField(help_text='2.0')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateTimeField()),
                ('author_name', models.CharField(help_text='Введите имя', max_length=100)),
                ('text', models.CharField(help_text='Текст отзыва', max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='review',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Car'),
        ),
        migrations.AddField(
            model_name='rent',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Car'),
        ),
        migrations.AddField(
            model_name='rent',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Manager'),
        ),
        migrations.AddField(
            model_name='rent',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Renter'),
        ),
    ]
