# Generated by Django 2.0.3 on 2018-05-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_auto_20180523_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='color',
        ),
        migrations.AddField(
            model_name='car',
            name='passengers',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rent',
            name='end_time',
            field=models.TimeField(help_text='Время возврата', verbose_name='Время возврата'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='start_time',
            field=models.TimeField(help_text='Время подачи', verbose_name='Время подачи'),
        ),
    ]
