# Generated by Django 2.0.3 on 2018-05-24 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_auto_20180523_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rent',
            name='day_end',
            field=models.DateField(verbose_name='День окончания'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='day_start',
            field=models.DateField(verbose_name='День начала'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='end_time',
            field=models.TimeField(verbose_name='Время возврата'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='pickup_point',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rent',
            name='return_point',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rent',
            name='start_time',
            field=models.TimeField(verbose_name='Время подачи'),
        ),
    ]
