# Generated by Django 2.0.3 on 2018-05-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_auto_20180524_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='licence_plate',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='badge_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='phone',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
