# Generated by Django 2.0.3 on 2018-05-24 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_auto_20180524_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
