# Generated by Django 2.0.3 on 2018-05-24 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_auto_20180524_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='badge_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manager',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
